initial commit for the main site part of this task. Check for a cms b…
waterloop/waterloop-website pull request #150
Opened 2022-07-22 03:59 UTC by G-Wang12

Added an old sponsors portion to the sponsors being displayed. Please check the cms for a branch with the same name for the cms part of the task.

2022-07-27 23:36 UTC, jmawloo requested changes

2022-07-27 23:36 UTC, jmawloo commented on src/api/server.ts
> +// tip from Gordon
**Ternary expression may help here**: {expr} ? {stmt1 if true} : {stmt2 if false}
Change line 3 to:
`const baseUrl = process.env.NODE_ENV === 'development' ? 'http://localhost:9000' : process.env.REACT_APP_BASE_URL`

2022-07-28 00:06 UTC, G-Wang12 commented
@jmawloo Added the new change! Should be ready to be merged! (I don't think I have permission to merge it myself)

2022-08-27 14:25 UTC, jmawloo approved these changes

2022-08-27 14:27 UTC, merged